### ISSUE TITLE
Will this be updated for Phalcon 2.0?

### ISSUE THREAD

**Issue by mayel** [saimusdev/dash-phalcon#6]
Would be much appreciated.

**Comment by saimusdev** [comment]
Probably yes! But first I want to leave a cleaner version for 1.3.0.
It wouldn't take much effort to adapt the docsets to version 2.0, but I'm going to make a different docset for each version.

**Comment by saimusdev** [comment]
Done. It's the first version. 
If there are any errors or something you are not happy with, just let me know ;)
Here you go: [Phalcon 2.docset](https://github.com/saimusdev/dash-phalcon/releases/download/2.0.0/Phalcon_2.docset.zip)

**Comment by saimusdev** [comment]
One more thing... remember than **when searching**, if you've got the Phalcon 1.3.0 docset added in Dash, you've got to **hit Enter** to view the possible docsets in which Dash found results for your search. Otherwise, it might look at first like the Phalcon 2 docset isn't working.

**Comment by mayel** [comment]
Thanks :)
